//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com", ConfigurationName="CategoryService.CategoryService")]
    public interface CategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getCategories(int startOffSet, int rowCount, bool withSpecs, bool withDeepest, bool withCatalog, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getCategoriesAsync(int startOffSet, int rowCount, bool withSpecs, bool withDeepest, bool withCatalog, string lang);
        
        // CODEGEN: Parameter 'categoryCodes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesResponse getCategoriesByCodes(Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesResponse> getCategoriesByCodesAsync(Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getCategoriesHavingVariantSpecs(string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getCategoriesHavingVariantSpecsAsync(string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getCategory(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getCategoryAsync(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryPermaServiceResponse getCategoryMetaData(string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryPermaServiceResponse> getCategoryMetaDataAsync(string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsServiceResponse getCategorySpecs(string categoryCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsServiceResponse> getCategorySpecsAsync(string categoryCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsWithDetailServiceResponse getCategorySpecsWithDetail(string categoryCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsWithDetailServiceResponse> getCategorySpecsWithDetailAsync(string categoryCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceVariantResponse getCategoryVariantSpecs(string categoryCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceVariantResponse> getCategoryVariantSpecsAsync(string categoryCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getDeepestCategories(int startOffSet, int rowCount, bool withSpecs, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getDeepestCategoriesAsync(int startOffSet, int rowCount, bool withSpecs, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getDepositCategories(string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getDepositCategoriesAsync(string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceAuditResponse getModifiedCategories(long changeTime, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceAuditResponse> getModifiedCategoriesAsync(long changeTime, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getParentCategories(bool withSpecs, bool withDeepest, bool withCatalog, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getParentCategoriesAsync(bool withSpecs, bool withDeepest, bool withCatalog, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getServiceName();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getServiceNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseAuditType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getSubCategories(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getSubCategoriesAsync(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryServiceResponse : baseResponse {
        
        private int categoryCountField;
        
        private bool categoryCountFieldSpecified;
        
        private categoryType[] categoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int categoryCount {
            get {
                return this.categoryCountField;
            }
            set {
                this.categoryCountField = value;
                this.RaisePropertyChanged("categoryCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoryCountSpecified {
            get {
                return this.categoryCountFieldSpecified;
            }
            set {
                this.categoryCountFieldSpecified = value;
                this.RaisePropertyChanged("categoryCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categoryType[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("categories");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoryCodeField;
        
        private string categoryNameField;
        
        private categorySpecType[] specsField;
        
        private bool deepestField;
        
        private bool deepestFieldSpecified;
        
        private bool hasCatalogField;
        
        private bool hasCatalogFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string categoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("categoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
                this.RaisePropertyChanged("categoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("spec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categorySpecType[] specs {
            get {
                return this.specsField;
            }
            set {
                this.specsField = value;
                this.RaisePropertyChanged("specs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deepest {
            get {
                return this.deepestField;
            }
            set {
                this.deepestField = value;
                this.RaisePropertyChanged("deepest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deepestSpecified {
            get {
                return this.deepestFieldSpecified;
            }
            set {
                this.deepestFieldSpecified = value;
                this.RaisePropertyChanged("deepestSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool hasCatalog {
            get {
                return this.hasCatalogField;
            }
            set {
                this.hasCatalogField = value;
                this.RaisePropertyChanged("hasCatalog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasCatalogSpecified {
            get {
                return this.hasCatalogFieldSpecified;
            }
            set {
                this.hasCatalogFieldSpecified = value;
                this.RaisePropertyChanged("hasCatalogSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categorySpecType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] valuesField;
        
        private string nameField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
                this.RaisePropertyChanged("required");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
                this.RaisePropertyChanged("requiredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryPermaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoryCodeField;
        
        private string categoryPermaField;
        
        private string[] breadCrumbsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string categoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("categoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoryPerma {
            get {
                return this.categoryPermaField;
            }
            set {
                this.categoryPermaField = value;
                this.RaisePropertyChanged("categoryPerma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("breadCrumb", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] breadCrumbs {
            get {
                return this.breadCrumbsField;
            }
            set {
                this.breadCrumbsField = value;
                this.RaisePropertyChanged("breadCrumbs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categorySpecValueType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int specIdField;
        
        private bool specIdFieldSpecified;
        
        private int parentSpecIdField;
        
        private bool parentSpecIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int specId {
            get {
                return this.specIdField;
            }
            set {
                this.specIdField = value;
                this.RaisePropertyChanged("specId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool specIdSpecified {
            get {
                return this.specIdFieldSpecified;
            }
            set {
                this.specIdFieldSpecified = value;
                this.RaisePropertyChanged("specIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int parentSpecId {
            get {
                return this.parentSpecIdField;
            }
            set {
                this.parentSpecIdField = value;
                this.RaisePropertyChanged("parentSpecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parentSpecIdSpecified {
            get {
                return this.parentSpecIdFieldSpecified;
            }
            set {
                this.parentSpecIdFieldSpecified = value;
                this.RaisePropertyChanged("parentSpecIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categorySpecWithDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categorySpecValueType[] valuesField;
        
        private string nameField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private string typeField;
        
        private int specIdField;
        
        private bool specIdFieldSpecified;
        
        private int childSpecIdField;
        
        private bool childSpecIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categorySpecValueType[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
                this.RaisePropertyChanged("required");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
                this.RaisePropertyChanged("requiredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int specId {
            get {
                return this.specIdField;
            }
            set {
                this.specIdField = value;
                this.RaisePropertyChanged("specId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool specIdSpecified {
            get {
                return this.specIdFieldSpecified;
            }
            set {
                this.specIdFieldSpecified = value;
                this.RaisePropertyChanged("specIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int childSpecId {
            get {
                return this.childSpecIdField;
            }
            set {
                this.childSpecIdField = value;
                this.RaisePropertyChanged("childSpecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool childSpecIdSpecified {
            get {
                return this.childSpecIdFieldSpecified;
            }
            set {
                this.childSpecIdFieldSpecified = value;
                this.RaisePropertyChanged("childSpecIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoryAuditType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public abstract partial class baseAuditType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string changeTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string changeType {
            get {
                return this.changeTypeField;
            }
            set {
                this.changeTypeField = value;
                this.RaisePropertyChanged("changeType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryAuditType : baseAuditType {
        
        private string categoryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string categoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("categoryCode");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryVariantSpecValueType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long valueIdField;
        
        private bool valueIdFieldSpecified;
        
        private string valueField;
        
        private int orderNumberField;
        
        private bool orderNumberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long valueId {
            get {
                return this.valueIdField;
            }
            set {
                this.valueIdField = value;
                this.RaisePropertyChanged("valueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueIdSpecified {
            get {
                return this.valueIdFieldSpecified;
            }
            set {
                this.valueIdFieldSpecified = value;
                this.RaisePropertyChanged("valueIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("orderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderNumberSpecified {
            get {
                return this.orderNumberFieldSpecified;
            }
            set {
                this.orderNumberFieldSpecified = value;
                this.RaisePropertyChanged("orderNumberSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryVariantSpecType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoryVariantSpecValueType[] specValuesField;
        
        private long nameIdField;
        
        private bool nameIdFieldSpecified;
        
        private string nameField;
        
        private string typeField;
        
        private int orderNumberField;
        
        private bool orderNumberFieldSpecified;
        
        private bool baseField;
        
        private bool baseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("specValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categoryVariantSpecValueType[] specValues {
            get {
                return this.specValuesField;
            }
            set {
                this.specValuesField = value;
                this.RaisePropertyChanged("specValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long nameId {
            get {
                return this.nameIdField;
            }
            set {
                this.nameIdField = value;
                this.RaisePropertyChanged("nameId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nameIdSpecified {
            get {
                return this.nameIdFieldSpecified;
            }
            set {
                this.nameIdFieldSpecified = value;
                this.RaisePropertyChanged("nameIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("orderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderNumberSpecified {
            get {
                return this.orderNumberFieldSpecified;
            }
            set {
                this.orderNumberFieldSpecified = value;
                this.RaisePropertyChanged("orderNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
                this.RaisePropertyChanged("base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseSpecified {
            get {
                return this.baseFieldSpecified;
            }
            set {
                this.baseFieldSpecified = value;
                this.RaisePropertyChanged("baseSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorIdField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private string viewMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
                this.RaisePropertyChanged("errorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string viewMessage {
            get {
                return this.viewMessageField;
            }
            set {
                this.viewMessageField = value;
                this.RaisePropertyChanged("viewMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoryPermaServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categorySpecsWithDetailServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoryServiceAuditResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categorySpecsServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoryServiceVariantResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoryServiceResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class baseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ackCodeField;
        
        private string responseTimeField;
        
        private errorType errorField;
        
        private string timeElapsedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ackCode {
            get {
                return this.ackCodeField;
            }
            set {
                this.ackCodeField = value;
                this.RaisePropertyChanged("ackCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public errorType error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string timeElapsed {
            get {
                return this.timeElapsedField;
            }
            set {
                this.timeElapsedField = value;
                this.RaisePropertyChanged("timeElapsed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryPermaServiceResponse : baseResponse {
        
        private int categoryCountField;
        
        private bool categoryCountFieldSpecified;
        
        private categoryPermaType[] categoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int categoryCount {
            get {
                return this.categoryCountField;
            }
            set {
                this.categoryCountField = value;
                this.RaisePropertyChanged("categoryCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoryCountSpecified {
            get {
                return this.categoryCountFieldSpecified;
            }
            set {
                this.categoryCountFieldSpecified = value;
                this.RaisePropertyChanged("categoryCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categoryPermaType[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("categories");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categorySpecsWithDetailServiceResponse : baseResponse {
        
        private categorySpecWithDetailType[] specsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("spec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categorySpecWithDetailType[] specs {
            get {
                return this.specsField;
            }
            set {
                this.specsField = value;
                this.RaisePropertyChanged("specs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryServiceAuditResponse : baseResponse {
        
        private int totalCountField;
        
        private bool totalCountFieldSpecified;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private categoryAuditType[] categoryAuditsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified {
            get {
                return this.totalCountFieldSpecified;
            }
            set {
                this.totalCountFieldSpecified = value;
                this.RaisePropertyChanged("totalCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("categoryAudit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categoryAuditType[] categoryAudits {
            get {
                return this.categoryAuditsField;
            }
            set {
                this.categoryAuditsField = value;
                this.RaisePropertyChanged("categoryAudits");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categorySpecsServiceResponse : baseResponse {
        
        private categorySpecType[] specsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("spec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categorySpecType[] specs {
            get {
                return this.specsField;
            }
            set {
                this.specsField = value;
                this.RaisePropertyChanged("specs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://category.anonymous.ws.listingapi.gg.com")]
    public partial class categoryServiceVariantResponse : baseResponse {
        
        private long specCountField;
        
        private bool specCountFieldSpecified;
        
        private categoryVariantSpecType[] specsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long specCount {
            get {
                return this.specCountField;
            }
            set {
                this.specCountField = value;
                this.RaisePropertyChanged("specCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool specCountSpecified {
            get {
                return this.specCountFieldSpecified;
            }
            set {
                this.specCountFieldSpecified = value;
                this.RaisePropertyChanged("specCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("spec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categoryVariantSpecType[] specs {
            get {
                return this.specsField;
            }
            set {
                this.specsField = value;
                this.RaisePropertyChanged("specs");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategoriesByCodes", WrapperNamespace="http://category.anonymous.ws.listingapi.gg.com", IsWrapped=true)]
    public partial class getCategoriesByCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] categoryCodes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool withSpecs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool withDeepest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public bool withCatalog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string lang;
        
        public getCategoriesByCodesRequest() {
        }
        
        public getCategoriesByCodesRequest(string[] categoryCodes, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            this.categoryCodes = categoryCodes;
            this.withSpecs = withSpecs;
            this.withDeepest = withDeepest;
            this.withCatalog = withCatalog;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategoriesByCodesResponse", WrapperNamespace="http://category.anonymous.ws.listingapi.gg.com", IsWrapped=true)]
    public partial class getCategoriesByCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse @return;
        
        public getCategoriesByCodesResponse() {
        }
        
        public getCategoriesByCodesResponse(Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoryServiceChannel : Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.CategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryServiceClient : System.ServiceModel.ClientBase<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.CategoryService>, Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.CategoryService {
        
        public CategoryServiceClient() {
        }
        
        public CategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getCategories(int startOffSet, int rowCount, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getCategories(startOffSet, rowCount, withSpecs, withDeepest, withCatalog, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getCategoriesAsync(int startOffSet, int rowCount, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getCategoriesAsync(startOffSet, rowCount, withSpecs, withDeepest, withCatalog, lang);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesResponse Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.CategoryService.getCategoriesByCodes(Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest request) {
            return base.Channel.getCategoriesByCodes(request);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getCategoriesByCodes(string[] categoryCodes, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest inValue = new Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest();
            inValue.categoryCodes = categoryCodes;
            inValue.withSpecs = withSpecs;
            inValue.withDeepest = withDeepest;
            inValue.withCatalog = withCatalog;
            inValue.lang = lang;
            Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesResponse retVal = ((Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.CategoryService)(this)).getCategoriesByCodes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesResponse> Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.CategoryService.getCategoriesByCodesAsync(Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest request) {
            return base.Channel.getCategoriesByCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesResponse> getCategoriesByCodesAsync(string[] categoryCodes, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest inValue = new Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.getCategoriesByCodesRequest();
            inValue.categoryCodes = categoryCodes;
            inValue.withSpecs = withSpecs;
            inValue.withDeepest = withDeepest;
            inValue.withCatalog = withCatalog;
            inValue.lang = lang;
            return ((Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.CategoryService)(this)).getCategoriesByCodesAsync(inValue);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getCategoriesHavingVariantSpecs(string lang) {
            return base.Channel.getCategoriesHavingVariantSpecs(lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getCategoriesHavingVariantSpecsAsync(string lang) {
            return base.Channel.getCategoriesHavingVariantSpecsAsync(lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getCategory(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getCategory(categoryCode, withSpecs, withDeepest, withCatalog, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getCategoryAsync(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getCategoryAsync(categoryCode, withSpecs, withDeepest, withCatalog, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryPermaServiceResponse getCategoryMetaData(string lang) {
            return base.Channel.getCategoryMetaData(lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryPermaServiceResponse> getCategoryMetaDataAsync(string lang) {
            return base.Channel.getCategoryMetaDataAsync(lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsServiceResponse getCategorySpecs(string categoryCode, string lang) {
            return base.Channel.getCategorySpecs(categoryCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsServiceResponse> getCategorySpecsAsync(string categoryCode, string lang) {
            return base.Channel.getCategorySpecsAsync(categoryCode, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsWithDetailServiceResponse getCategorySpecsWithDetail(string categoryCode, string lang) {
            return base.Channel.getCategorySpecsWithDetail(categoryCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categorySpecsWithDetailServiceResponse> getCategorySpecsWithDetailAsync(string categoryCode, string lang) {
            return base.Channel.getCategorySpecsWithDetailAsync(categoryCode, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceVariantResponse getCategoryVariantSpecs(string categoryCode, string lang) {
            return base.Channel.getCategoryVariantSpecs(categoryCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceVariantResponse> getCategoryVariantSpecsAsync(string categoryCode, string lang) {
            return base.Channel.getCategoryVariantSpecsAsync(categoryCode, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getDeepestCategories(int startOffSet, int rowCount, bool withSpecs, string lang) {
            return base.Channel.getDeepestCategories(startOffSet, rowCount, withSpecs, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getDeepestCategoriesAsync(int startOffSet, int rowCount, bool withSpecs, string lang) {
            return base.Channel.getDeepestCategoriesAsync(startOffSet, rowCount, withSpecs, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getDepositCategories(string lang) {
            return base.Channel.getDepositCategories(lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getDepositCategoriesAsync(string lang) {
            return base.Channel.getDepositCategoriesAsync(lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceAuditResponse getModifiedCategories(long changeTime, int startOffSet, int rowCount, string lang) {
            return base.Channel.getModifiedCategories(changeTime, startOffSet, rowCount, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceAuditResponse> getModifiedCategoriesAsync(long changeTime, int startOffSet, int rowCount, string lang) {
            return base.Channel.getModifiedCategoriesAsync(changeTime, startOffSet, rowCount, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getParentCategories(bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getParentCategories(withSpecs, withDeepest, withCatalog, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getParentCategoriesAsync(bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getParentCategoriesAsync(withSpecs, withDeepest, withCatalog, lang);
        }
        
        public string getServiceName() {
            return base.Channel.getServiceName();
        }
        
        public System.Threading.Tasks.Task<string> getServiceNameAsync() {
            return base.Channel.getServiceNameAsync();
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse getSubCategories(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getSubCategories(categoryCode, withSpecs, withDeepest, withCatalog, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.CategoryService.categoryServiceResponse> getSubCategoriesAsync(string categoryCode, bool withSpecs, bool withDeepest, bool withCatalog, string lang) {
            return base.Channel.getSubCategoriesAsync(categoryCode, withSpecs, withDeepest, withCatalog, lang);
        }
    }
}
