//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com", ConfigurationName="IndividualSaleService.IndividualSaleService")]
    public interface IndividualSaleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse cancelSale(string apiKey, string sign, long time, string saleCode, int reasonId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> cancelSaleAsync(string apiKey, string sign, long time, string saleCode, int reasonId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.accountTransactionListResponse getAccountTransactions(string apiKey, string sign, long time, string startDate, string endDate, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.accountTransactionListResponse> getAccountTransactionsAsync(string apiKey, string sign, long time, string startDate, string endDate, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceBuyerResponse getItemBuyers(string apiKey, string sign, long time, string byStatus, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceBuyerResponse> getItemBuyersAsync(string apiKey, string sign, long time, string byStatus, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceCancelReasonResponse getReasonsToCancelSale(string apiKey, string sign, long time, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceCancelReasonResponse> getReasonsToCancelSaleAsync(string apiKey, string sign, long time, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse getSale(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse> getSaleAsync(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse getSales(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse> getSalesAsync(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse getSalesByDateRange(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string startDate, string endDate, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse> getSalesByDateRangeAsync(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string startDate, string endDate, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getServiceName();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getServiceNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse giveApprovalForRemandedItem(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> giveApprovalForRemandedItemAsync(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse giveRateAndComment(string apiKey, string sign, long time, string userType, int productId, int rate, string comment, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse> giveRateAndCommentAsync(string apiKey, string sign, long time, string userType, int productId, int rate, string comment, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse receiveRemandedItem(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> receiveRemandedItemAsync(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse remindForApproval(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> remindForApprovalAsync(string apiKey, string sign, long time, string saleCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse removeSaleFromList(string apiKey, string sign, long time, string saleCode, string userType, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> removeSaleFromListAsync(string apiKey, string sign, long time, string saleCode, string userType, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse replySaleComment(string apiKey, string sign, long time, string userType, int productId, string comment, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse> replySaleCommentAsync(string apiKey, string sign, long time, string userType, int productId, string comment, string lang);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class messageServiceResponse : baseResponse {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(commonSaleResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saleServiceCancelReasonResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saleServiceBuyerResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(accountTransactionListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(messageServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saleServiceResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class baseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ackCodeField;
        
        private string responseTimeField;
        
        private errorType errorField;
        
        private string timeElapsedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ackCode {
            get {
                return this.ackCodeField;
            }
            set {
                this.ackCodeField = value;
                this.RaisePropertyChanged("ackCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public errorType error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string timeElapsed {
            get {
                return this.timeElapsedField;
            }
            set {
                this.timeElapsedField = value;
                this.RaisePropertyChanged("timeElapsed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorIdField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private string viewMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
                this.RaisePropertyChanged("errorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string viewMessage {
            get {
                return this.viewMessageField;
            }
            set {
                this.viewMessageField = value;
                this.RaisePropertyChanged("viewMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class saleReasonType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class saleBuyerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nickField;
        
        private long saleCountField;
        
        private bool saleCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
                this.RaisePropertyChanged("nick");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long saleCount {
            get {
                return this.saleCountField;
            }
            set {
                this.saleCountField = value;
                this.RaisePropertyChanged("saleCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saleCountSpecified {
            get {
                return this.saleCountFieldSpecified;
            }
            set {
                this.saleCountFieldSpecified = value;
                this.RaisePropertyChanged("saleCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class accountTransactionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string saleCodeField;
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string productTitleField;
        
        private string buyerNickField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private decimal ggCommissionField;
        
        private bool ggCommissionFieldSpecified;
        
        private decimal commissionPriceField;
        
        private bool commissionPriceFieldSpecified;
        
        private decimal paidPriceField;
        
        private bool paidPriceFieldSpecified;
        
        private string approveDateField;
        
        private string approveField;
        
        private string accountNumberField;
        
        private string ibanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string saleCode {
            get {
                return this.saleCodeField;
            }
            set {
                this.saleCodeField = value;
                this.RaisePropertyChanged("saleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productTitle {
            get {
                return this.productTitleField;
            }
            set {
                this.productTitleField = value;
                this.RaisePropertyChanged("productTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string buyerNick {
            get {
                return this.buyerNickField;
            }
            set {
                this.buyerNickField = value;
                this.RaisePropertyChanged("buyerNick");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ggCommission {
            get {
                return this.ggCommissionField;
            }
            set {
                this.ggCommissionField = value;
                this.RaisePropertyChanged("ggCommission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ggCommissionSpecified {
            get {
                return this.ggCommissionFieldSpecified;
            }
            set {
                this.ggCommissionFieldSpecified = value;
                this.RaisePropertyChanged("ggCommissionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal commissionPrice {
            get {
                return this.commissionPriceField;
            }
            set {
                this.commissionPriceField = value;
                this.RaisePropertyChanged("commissionPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commissionPriceSpecified {
            get {
                return this.commissionPriceFieldSpecified;
            }
            set {
                this.commissionPriceFieldSpecified = value;
                this.RaisePropertyChanged("commissionPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal paidPrice {
            get {
                return this.paidPriceField;
            }
            set {
                this.paidPriceField = value;
                this.RaisePropertyChanged("paidPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paidPriceSpecified {
            get {
                return this.paidPriceFieldSpecified;
            }
            set {
                this.paidPriceFieldSpecified = value;
                this.RaisePropertyChanged("paidPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string approveDate {
            get {
                return this.approveDateField;
            }
            set {
                this.approveDateField = value;
                this.RaisePropertyChanged("approveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string approve {
            get {
                return this.approveField;
            }
            set {
                this.approveField = value;
                this.RaisePropertyChanged("approve");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string iban {
            get {
                return this.ibanField;
            }
            set {
                this.ibanField = value;
                this.RaisePropertyChanged("iban");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class itemVariantSpecType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private int quantityField;
        
        private bool quantityFieldSpecified;
        
        private int soldQuantityField;
        
        private bool soldQuantityFieldSpecified;
        
        private string stockCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int soldQuantity {
            get {
                return this.soldQuantityField;
            }
            set {
                this.soldQuantityField = value;
                this.RaisePropertyChanged("soldQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool soldQuantitySpecified {
            get {
                return this.soldQuantityFieldSpecified;
            }
            set {
                this.soldQuantityFieldSpecified = value;
                this.RaisePropertyChanged("soldQuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stockCode {
            get {
                return this.stockCodeField;
            }
            set {
                this.stockCodeField = value;
                this.RaisePropertyChanged("stockCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class saleInvoiceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullnameField;
        
        private string addressField;
        
        private string districtField;
        
        private int cityCodeField;
        
        private bool cityCodeFieldSpecified;
        
        private string zipCodeField;
        
        private string phoneNumberField;
        
        private string taxOfficeField;
        
        private string taxNumberField;
        
        private string companyTitleField;
        
        private string tcCertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
                this.RaisePropertyChanged("fullname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cityCodeSpecified {
            get {
                return this.cityCodeFieldSpecified;
            }
            set {
                this.cityCodeFieldSpecified = value;
                this.RaisePropertyChanged("cityCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string taxOffice {
            get {
                return this.taxOfficeField;
            }
            set {
                this.taxOfficeField = value;
                this.RaisePropertyChanged("taxOffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string taxNumber {
            get {
                return this.taxNumberField;
            }
            set {
                this.taxNumberField = value;
                this.RaisePropertyChanged("taxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string companyTitle {
            get {
                return this.companyTitleField;
            }
            set {
                this.companyTitleField = value;
                this.RaisePropertyChanged("companyTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string tcCertificate {
            get {
                return this.tcCertificateField;
            }
            set {
                this.tcCertificateField = value;
                this.RaisePropertyChanged("tcCertificate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class orderBuyerInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string nameField;
        
        private string surnameField;
        
        private string phoneField;
        
        private string addressField;
        
        private string districtField;
        
        private string cityField;
        
        private string zipCodeField;
        
        private int processCountField;
        
        private bool processCountFieldSpecified;
        
        private int ratePercentageField;
        
        private bool ratePercentageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int processCount {
            get {
                return this.processCountField;
            }
            set {
                this.processCountField = value;
                this.RaisePropertyChanged("processCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processCountSpecified {
            get {
                return this.processCountFieldSpecified;
            }
            set {
                this.processCountFieldSpecified = value;
                this.RaisePropertyChanged("processCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int ratePercentage {
            get {
                return this.ratePercentageField;
            }
            set {
                this.ratePercentageField = value;
                this.RaisePropertyChanged("ratePercentage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ratePercentageSpecified {
            get {
                return this.ratePercentageFieldSpecified;
            }
            set {
                this.ratePercentageFieldSpecified = value;
                this.RaisePropertyChanged("ratePercentageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class saleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string saleCodeField;
        
        private string statusField;
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string productTitleField;
        
        private string priceField;
        
        private string cargoPaymentField;
        
        private int amountField;
        
        private bool amountFieldSpecified;
        
        private string endDateField;
        
        private orderBuyerInfoType buyerInfoField;
        
        private string changeStatusField;
        
        private string thumbImageLinkField;
        
        private string lastActionDateField;
        
        private System.Nullable<int>[] waitingProcessesField;
        
        private saleInvoiceType invoiceInfoField;
        
        private long variantIdField;
        
        private bool variantIdFieldSpecified;
        
        private itemVariantSpecType[] variantSpecsField;
        
        private string moneyDateField;
        
        private string cargoApprovementDateField;
        
        private string itemIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string saleCode {
            get {
                return this.saleCodeField;
            }
            set {
                this.saleCodeField = value;
                this.RaisePropertyChanged("saleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string productTitle {
            get {
                return this.productTitleField;
            }
            set {
                this.productTitleField = value;
                this.RaisePropertyChanged("productTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cargoPayment {
            get {
                return this.cargoPaymentField;
            }
            set {
                this.cargoPaymentField = value;
                this.RaisePropertyChanged("cargoPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public orderBuyerInfoType buyerInfo {
            get {
                return this.buyerInfoField;
            }
            set {
                this.buyerInfoField = value;
                this.RaisePropertyChanged("buyerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string changeStatus {
            get {
                return this.changeStatusField;
            }
            set {
                this.changeStatusField = value;
                this.RaisePropertyChanged("changeStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string thumbImageLink {
            get {
                return this.thumbImageLinkField;
            }
            set {
                this.thumbImageLinkField = value;
                this.RaisePropertyChanged("thumbImageLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string lastActionDate {
            get {
                return this.lastActionDateField;
            }
            set {
                this.lastActionDateField = value;
                this.RaisePropertyChanged("lastActionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("waitingProcess", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] waitingProcesses {
            get {
                return this.waitingProcessesField;
            }
            set {
                this.waitingProcessesField = value;
                this.RaisePropertyChanged("waitingProcesses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public saleInvoiceType invoiceInfo {
            get {
                return this.invoiceInfoField;
            }
            set {
                this.invoiceInfoField = value;
                this.RaisePropertyChanged("invoiceInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public long variantId {
            get {
                return this.variantIdField;
            }
            set {
                this.variantIdField = value;
                this.RaisePropertyChanged("variantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variantIdSpecified {
            get {
                return this.variantIdFieldSpecified;
            }
            set {
                this.variantIdFieldSpecified = value;
                this.RaisePropertyChanged("variantIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("variantSpec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public itemVariantSpecType[] variantSpecs {
            get {
                return this.variantSpecsField;
            }
            set {
                this.variantSpecsField = value;
                this.RaisePropertyChanged("variantSpecs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string moneyDate {
            get {
                return this.moneyDateField;
            }
            set {
                this.moneyDateField = value;
                this.RaisePropertyChanged("moneyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string cargoApprovementDate {
            get {
                return this.cargoApprovementDateField;
            }
            set {
                this.cargoApprovementDateField = value;
                this.RaisePropertyChanged("cargoApprovementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string itemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("itemId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class commonSaleResponse : baseResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class saleServiceCancelReasonResponse : baseResponse {
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private saleReasonType[] reasonsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("reason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public saleReasonType[] reasons {
            get {
                return this.reasonsField;
            }
            set {
                this.reasonsField = value;
                this.RaisePropertyChanged("reasons");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class saleServiceBuyerResponse : baseResponse {
        
        private int totalCountField;
        
        private bool totalCountFieldSpecified;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private saleBuyerType[] itemBuyersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified {
            get {
                return this.totalCountFieldSpecified;
            }
            set {
                this.totalCountFieldSpecified = value;
                this.RaisePropertyChanged("totalCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemBuyer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public saleBuyerType[] itemBuyers {
            get {
                return this.itemBuyersField;
            }
            set {
                this.itemBuyersField = value;
                this.RaisePropertyChanged("itemBuyers");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class accountTransactionListResponse : baseResponse {
        
        private int totalCountField;
        
        private bool totalCountFieldSpecified;
        
        private accountTransactionType[] salesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified {
            get {
                return this.totalCountFieldSpecified;
            }
            set {
                this.totalCountFieldSpecified = value;
                this.RaisePropertyChanged("totalCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public accountTransactionType[] sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
                this.RaisePropertyChanged("sales");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sale.individual.ws.listingapi.gg.com")]
    public partial class saleServiceResponse : baseResponse {
        
        private int saleCountField;
        
        private bool saleCountFieldSpecified;
        
        private saleType[] salesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int saleCount {
            get {
                return this.saleCountField;
            }
            set {
                this.saleCountField = value;
                this.RaisePropertyChanged("saleCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saleCountSpecified {
            get {
                return this.saleCountFieldSpecified;
            }
            set {
                this.saleCountFieldSpecified = value;
                this.RaisePropertyChanged("saleCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public saleType[] sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
                this.RaisePropertyChanged("sales");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IndividualSaleServiceChannel : Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.IndividualSaleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndividualSaleServiceClient : System.ServiceModel.ClientBase<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.IndividualSaleService>, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.IndividualSaleService {
        
        public IndividualSaleServiceClient() {
        }
        
        public IndividualSaleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndividualSaleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndividualSaleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndividualSaleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse cancelSale(string apiKey, string sign, long time, string saleCode, int reasonId, string lang) {
            return base.Channel.cancelSale(apiKey, sign, time, saleCode, reasonId, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> cancelSaleAsync(string apiKey, string sign, long time, string saleCode, int reasonId, string lang) {
            return base.Channel.cancelSaleAsync(apiKey, sign, time, saleCode, reasonId, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.accountTransactionListResponse getAccountTransactions(string apiKey, string sign, long time, string startDate, string endDate, int startOffSet, int rowCount, string lang) {
            return base.Channel.getAccountTransactions(apiKey, sign, time, startDate, endDate, startOffSet, rowCount, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.accountTransactionListResponse> getAccountTransactionsAsync(string apiKey, string sign, long time, string startDate, string endDate, int startOffSet, int rowCount, string lang) {
            return base.Channel.getAccountTransactionsAsync(apiKey, sign, time, startDate, endDate, startOffSet, rowCount, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceBuyerResponse getItemBuyers(string apiKey, string sign, long time, string byStatus, int startOffSet, int rowCount, string lang) {
            return base.Channel.getItemBuyers(apiKey, sign, time, byStatus, startOffSet, rowCount, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceBuyerResponse> getItemBuyersAsync(string apiKey, string sign, long time, string byStatus, int startOffSet, int rowCount, string lang) {
            return base.Channel.getItemBuyersAsync(apiKey, sign, time, byStatus, startOffSet, rowCount, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceCancelReasonResponse getReasonsToCancelSale(string apiKey, string sign, long time, string lang) {
            return base.Channel.getReasonsToCancelSale(apiKey, sign, time, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceCancelReasonResponse> getReasonsToCancelSaleAsync(string apiKey, string sign, long time, string lang) {
            return base.Channel.getReasonsToCancelSaleAsync(apiKey, sign, time, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse getSale(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.getSale(apiKey, sign, time, saleCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse> getSaleAsync(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.getSaleAsync(apiKey, sign, time, saleCode, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse getSales(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string lang) {
            return base.Channel.getSales(apiKey, sign, time, startOffSet, rowCount, withData, byStatus, byUser, orderBy, orderType, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse> getSalesAsync(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string lang) {
            return base.Channel.getSalesAsync(apiKey, sign, time, startOffSet, rowCount, withData, byStatus, byUser, orderBy, orderType, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse getSalesByDateRange(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string startDate, string endDate, string lang) {
            return base.Channel.getSalesByDateRange(apiKey, sign, time, startOffSet, rowCount, withData, byStatus, byUser, orderBy, orderType, startDate, endDate, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.saleServiceResponse> getSalesByDateRangeAsync(string apiKey, string sign, long time, int startOffSet, int rowCount, bool withData, string byStatus, string byUser, string orderBy, string orderType, string startDate, string endDate, string lang) {
            return base.Channel.getSalesByDateRangeAsync(apiKey, sign, time, startOffSet, rowCount, withData, byStatus, byUser, orderBy, orderType, startDate, endDate, lang);
        }
        
        public string getServiceName() {
            return base.Channel.getServiceName();
        }
        
        public System.Threading.Tasks.Task<string> getServiceNameAsync() {
            return base.Channel.getServiceNameAsync();
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse giveApprovalForRemandedItem(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.giveApprovalForRemandedItem(apiKey, sign, time, saleCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> giveApprovalForRemandedItemAsync(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.giveApprovalForRemandedItemAsync(apiKey, sign, time, saleCode, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse giveRateAndComment(string apiKey, string sign, long time, string userType, int productId, int rate, string comment, string lang) {
            return base.Channel.giveRateAndComment(apiKey, sign, time, userType, productId, rate, comment, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse> giveRateAndCommentAsync(string apiKey, string sign, long time, string userType, int productId, int rate, string comment, string lang) {
            return base.Channel.giveRateAndCommentAsync(apiKey, sign, time, userType, productId, rate, comment, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse receiveRemandedItem(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.receiveRemandedItem(apiKey, sign, time, saleCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> receiveRemandedItemAsync(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.receiveRemandedItemAsync(apiKey, sign, time, saleCode, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse remindForApproval(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.remindForApproval(apiKey, sign, time, saleCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> remindForApprovalAsync(string apiKey, string sign, long time, string saleCode, string lang) {
            return base.Channel.remindForApprovalAsync(apiKey, sign, time, saleCode, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse removeSaleFromList(string apiKey, string sign, long time, string saleCode, string userType, string lang) {
            return base.Channel.removeSaleFromList(apiKey, sign, time, saleCode, userType, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.messageServiceResponse> removeSaleFromListAsync(string apiKey, string sign, long time, string saleCode, string userType, string lang) {
            return base.Channel.removeSaleFromListAsync(apiKey, sign, time, saleCode, userType, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse replySaleComment(string apiKey, string sign, long time, string userType, int productId, string comment, string lang) {
            return base.Channel.replySaleComment(apiKey, sign, time, userType, productId, comment, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualSaleService.commonSaleResponse> replySaleCommentAsync(string apiKey, string sign, long time, string userType, int productId, string comment, string lang) {
            return base.Channel.replySaleCommentAsync(apiKey, sign, time, userType, productId, comment, lang);
        }
    }
}
