//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://application.individual.ws.listingapi.gg.com", ConfigurationName="IndividualAddressService.IndividualAddressService")]
    public interface IndividualAddressService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse createNewAddress(string apiKey, string sign, long time, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> createNewAddressAsync(string apiKey, string sign, long time, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse deleteAddress(string apiKey, string sign, long time, int addressId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> deleteAddressAsync(string apiKey, string sign, long time, int addressId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse getAddressDetail(string apiKey, string sign, long time, int addressId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse> getAddressDetailAsync(string apiKey, string sign, long time, int addressId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceListResponse getAddressList(string apiKey, string sign, long time, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceListResponse> getAddressListAsync(string apiKey, string sign, long time, int startOffSet, int rowCount, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse getDefaultAddressDetail(string apiKey, string sign, long time, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse> getDefaultAddressDetailAsync(string apiKey, string sign, long time, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getServiceName();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getServiceNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse makeAddressAsDefault(string apiKey, string sign, long time, int addressId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> makeAddressAsDefaultAsync(string apiKey, string sign, long time, int addressId, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse updateAddress(string apiKey, string sign, long time, int addressId, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> updateAddressAsync(string apiKey, string sign, long time, int addressId, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.individual.ws.listingapi.gg.com")]
    public partial class addressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int addressIdField;
        
        private bool addressIdFieldSpecified;
        
        private bool isDefaultField;
        
        private bool isDefaultFieldSpecified;
        
        private string nameField;
        
        private string surnameField;
        
        private string aliasField;
        
        private string addressField;
        
        private string districtField;
        
        private string zipCodeField;
        
        private cityType cityField;
        
        private string phoneNumberField;
        
        private string gsmNumberField;
        
        private string faxNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int addressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
                this.RaisePropertyChanged("addressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addressIdSpecified {
            get {
                return this.addressIdFieldSpecified;
            }
            set {
                this.addressIdFieldSpecified = value;
                this.RaisePropertyChanged("addressIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
                this.RaisePropertyChanged("isDefault");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDefaultSpecified {
            get {
                return this.isDefaultFieldSpecified;
            }
            set {
                this.isDefaultFieldSpecified = value;
                this.RaisePropertyChanged("isDefaultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public cityType city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string gsmNumber {
            get {
                return this.gsmNumberField;
            }
            set {
                this.gsmNumberField = value;
                this.RaisePropertyChanged("gsmNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string faxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("faxNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.individual.ws.listingapi.gg.com")]
    public partial class cityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int trCodeField;
        
        private bool trCodeFieldSpecified;
        
        private string cityNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int trCode {
            get {
                return this.trCodeField;
            }
            set {
                this.trCodeField = value;
                this.RaisePropertyChanged("trCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trCodeSpecified {
            get {
                return this.trCodeFieldSpecified;
            }
            set {
                this.trCodeFieldSpecified = value;
                this.RaisePropertyChanged("trCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.individual.ws.listingapi.gg.com")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorIdField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private string viewMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
                this.RaisePropertyChanged("errorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string viewMessage {
            get {
                return this.viewMessageField;
            }
            set {
                this.viewMessageField = value;
                this.RaisePropertyChanged("viewMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addressServiceDetailResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addressServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addressServiceListResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.individual.ws.listingapi.gg.com")]
    public partial class baseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ackCodeField;
        
        private string responseTimeField;
        
        private errorType errorField;
        
        private string timeElapsedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ackCode {
            get {
                return this.ackCodeField;
            }
            set {
                this.ackCodeField = value;
                this.RaisePropertyChanged("ackCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public errorType error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string timeElapsed {
            get {
                return this.timeElapsedField;
            }
            set {
                this.timeElapsedField = value;
                this.RaisePropertyChanged("timeElapsed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.individual.ws.listingapi.gg.com")]
    public partial class addressServiceDetailResponse : baseResponse {
        
        private addressType addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public addressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.individual.ws.listingapi.gg.com")]
    public partial class addressServiceResponse : baseResponse {
        
        private int addressIdField;
        
        private bool addressIdFieldSpecified;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int addressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
                this.RaisePropertyChanged("addressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addressIdSpecified {
            get {
                return this.addressIdFieldSpecified;
            }
            set {
                this.addressIdFieldSpecified = value;
                this.RaisePropertyChanged("addressIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.individual.ws.listingapi.gg.com")]
    public partial class addressServiceListResponse : baseResponse {
        
        private int totalCountField;
        
        private bool totalCountFieldSpecified;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private addressType[] addressesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified {
            get {
                return this.totalCountFieldSpecified;
            }
            set {
                this.totalCountFieldSpecified = value;
                this.RaisePropertyChanged("totalCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public addressType[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("addresses");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IndividualAddressServiceChannel : Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.IndividualAddressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndividualAddressServiceClient : System.ServiceModel.ClientBase<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.IndividualAddressService>, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.IndividualAddressService {
        
        public IndividualAddressServiceClient() {
        }
        
        public IndividualAddressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndividualAddressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndividualAddressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndividualAddressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse createNewAddress(string apiKey, string sign, long time, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang) {
            return base.Channel.createNewAddress(apiKey, sign, time, address, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> createNewAddressAsync(string apiKey, string sign, long time, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang) {
            return base.Channel.createNewAddressAsync(apiKey, sign, time, address, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse deleteAddress(string apiKey, string sign, long time, int addressId, string lang) {
            return base.Channel.deleteAddress(apiKey, sign, time, addressId, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> deleteAddressAsync(string apiKey, string sign, long time, int addressId, string lang) {
            return base.Channel.deleteAddressAsync(apiKey, sign, time, addressId, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse getAddressDetail(string apiKey, string sign, long time, int addressId, string lang) {
            return base.Channel.getAddressDetail(apiKey, sign, time, addressId, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse> getAddressDetailAsync(string apiKey, string sign, long time, int addressId, string lang) {
            return base.Channel.getAddressDetailAsync(apiKey, sign, time, addressId, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceListResponse getAddressList(string apiKey, string sign, long time, int startOffSet, int rowCount, string lang) {
            return base.Channel.getAddressList(apiKey, sign, time, startOffSet, rowCount, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceListResponse> getAddressListAsync(string apiKey, string sign, long time, int startOffSet, int rowCount, string lang) {
            return base.Channel.getAddressListAsync(apiKey, sign, time, startOffSet, rowCount, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse getDefaultAddressDetail(string apiKey, string sign, long time, string lang) {
            return base.Channel.getDefaultAddressDetail(apiKey, sign, time, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceDetailResponse> getDefaultAddressDetailAsync(string apiKey, string sign, long time, string lang) {
            return base.Channel.getDefaultAddressDetailAsync(apiKey, sign, time, lang);
        }
        
        public string getServiceName() {
            return base.Channel.getServiceName();
        }
        
        public System.Threading.Tasks.Task<string> getServiceNameAsync() {
            return base.Channel.getServiceNameAsync();
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse makeAddressAsDefault(string apiKey, string sign, long time, int addressId, string lang) {
            return base.Channel.makeAddressAsDefault(apiKey, sign, time, addressId, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> makeAddressAsDefaultAsync(string apiKey, string sign, long time, int addressId, string lang) {
            return base.Channel.makeAddressAsDefaultAsync(apiKey, sign, time, addressId, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse updateAddress(string apiKey, string sign, long time, int addressId, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang) {
            return base.Channel.updateAddress(apiKey, sign, time, addressId, address, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressServiceResponse> updateAddressAsync(string apiKey, string sign, long time, int addressId, Ophelia.Integration.C2CMarket.GittiGidiyor.IndividualAddressService.addressType address, string lang) {
            return base.Channel.updateAddressAsync(apiKey, sign, time, addressId, address, lang);
        }
    }
}
