//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com", ConfigurationName="SearchService.SearchService")]
    public interface SearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getServiceName();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getServiceNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse search(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse> searchAsync(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse searchByVersion(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string version, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse> searchByVersionAsync(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string version, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceCategoryResponse searchForCategories(string categoryCode, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceCategoryResponse> searchForCategoriesAsync(string categoryCode, string lang);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class searchCriteriaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string formatField;
        
        private bool freeShippingField;
        
        private bool freeShippingFieldSpecified;
        
        private bool startFromOneTLField;
        
        private bool startFromOneTLFieldSpecified;
        
        private bool catalogOptionField;
        
        private bool catalogOptionFieldSpecified;
        
        private bool newProductField;
        
        private bool newProductFieldSpecified;
        
        private double minPriceField;
        
        private bool minPriceFieldSpecified;
        
        private double maxPriceField;
        
        private bool maxPriceFieldSpecified;
        
        private int cityField;
        
        private bool cityFieldSpecified;
        
        private int newItemsField;
        
        private bool newItemsFieldSpecified;
        
        private int runOutItemsField;
        
        private bool runOutItemsFieldSpecified;
        
        private int finishedItemsField;
        
        private bool finishedItemsFieldSpecified;
        
        private string sellerField;
        
        private bool sellerExcludedField;
        
        private bool sellerExcludedFieldSpecified;
        
        private string categoryCodeField;
        
        private int catalogIdField;
        
        private bool catalogIdFieldSpecified;
        
        private categorySpecCriteriaType[] categorySpecsField;
        
        private bool returnSpecsField;
        
        private bool returnSpecsFieldSpecified;
        
        private bool newProductWithNoSpecField;
        
        private bool newProductWithNoSpecFieldSpecified;
        
        private bool storeVisibilityField;
        
        private bool storeVisibilityFieldSpecified;
        
        private int storeTypeField;
        
        private bool storeTypeFieldSpecified;
        
        private int storeCategoryIdField;
        
        private bool storeCategoryIdFieldSpecified;
        
        private int categoryLevelField;
        
        private bool categoryLevelFieldSpecified;
        
        private facetFields facetFieldsField;
        
        private int parkCategoryIdField;
        
        private bool parkCategoryIdFieldSpecified;
        
        private bool parkItemsField;
        
        private bool parkItemsFieldSpecified;
        
        private bool returnImagesField;
        
        private bool returnImagesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool freeShipping {
            get {
                return this.freeShippingField;
            }
            set {
                this.freeShippingField = value;
                this.RaisePropertyChanged("freeShipping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool freeShippingSpecified {
            get {
                return this.freeShippingFieldSpecified;
            }
            set {
                this.freeShippingFieldSpecified = value;
                this.RaisePropertyChanged("freeShippingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool startFromOneTL {
            get {
                return this.startFromOneTLField;
            }
            set {
                this.startFromOneTLField = value;
                this.RaisePropertyChanged("startFromOneTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startFromOneTLSpecified {
            get {
                return this.startFromOneTLFieldSpecified;
            }
            set {
                this.startFromOneTLFieldSpecified = value;
                this.RaisePropertyChanged("startFromOneTLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool catalogOption {
            get {
                return this.catalogOptionField;
            }
            set {
                this.catalogOptionField = value;
                this.RaisePropertyChanged("catalogOption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool catalogOptionSpecified {
            get {
                return this.catalogOptionFieldSpecified;
            }
            set {
                this.catalogOptionFieldSpecified = value;
                this.RaisePropertyChanged("catalogOptionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool newProduct {
            get {
                return this.newProductField;
            }
            set {
                this.newProductField = value;
                this.RaisePropertyChanged("newProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newProductSpecified {
            get {
                return this.newProductFieldSpecified;
            }
            set {
                this.newProductFieldSpecified = value;
                this.RaisePropertyChanged("newProductSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double minPrice {
            get {
                return this.minPriceField;
            }
            set {
                this.minPriceField = value;
                this.RaisePropertyChanged("minPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minPriceSpecified {
            get {
                return this.minPriceFieldSpecified;
            }
            set {
                this.minPriceFieldSpecified = value;
                this.RaisePropertyChanged("minPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double maxPrice {
            get {
                return this.maxPriceField;
            }
            set {
                this.maxPriceField = value;
                this.RaisePropertyChanged("maxPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPriceSpecified {
            get {
                return this.maxPriceFieldSpecified;
            }
            set {
                this.maxPriceFieldSpecified = value;
                this.RaisePropertyChanged("maxPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citySpecified {
            get {
                return this.cityFieldSpecified;
            }
            set {
                this.cityFieldSpecified = value;
                this.RaisePropertyChanged("citySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int newItems {
            get {
                return this.newItemsField;
            }
            set {
                this.newItemsField = value;
                this.RaisePropertyChanged("newItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newItemsSpecified {
            get {
                return this.newItemsFieldSpecified;
            }
            set {
                this.newItemsFieldSpecified = value;
                this.RaisePropertyChanged("newItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int runOutItems {
            get {
                return this.runOutItemsField;
            }
            set {
                this.runOutItemsField = value;
                this.RaisePropertyChanged("runOutItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool runOutItemsSpecified {
            get {
                return this.runOutItemsFieldSpecified;
            }
            set {
                this.runOutItemsFieldSpecified = value;
                this.RaisePropertyChanged("runOutItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int finishedItems {
            get {
                return this.finishedItemsField;
            }
            set {
                this.finishedItemsField = value;
                this.RaisePropertyChanged("finishedItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finishedItemsSpecified {
            get {
                return this.finishedItemsFieldSpecified;
            }
            set {
                this.finishedItemsFieldSpecified = value;
                this.RaisePropertyChanged("finishedItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string seller {
            get {
                return this.sellerField;
            }
            set {
                this.sellerField = value;
                this.RaisePropertyChanged("seller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool sellerExcluded {
            get {
                return this.sellerExcludedField;
            }
            set {
                this.sellerExcludedField = value;
                this.RaisePropertyChanged("sellerExcluded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sellerExcludedSpecified {
            get {
                return this.sellerExcludedFieldSpecified;
            }
            set {
                this.sellerExcludedFieldSpecified = value;
                this.RaisePropertyChanged("sellerExcludedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string categoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("categoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int catalogId {
            get {
                return this.catalogIdField;
            }
            set {
                this.catalogIdField = value;
                this.RaisePropertyChanged("catalogId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool catalogIdSpecified {
            get {
                return this.catalogIdFieldSpecified;
            }
            set {
                this.catalogIdFieldSpecified = value;
                this.RaisePropertyChanged("catalogIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("categorySpec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categorySpecCriteriaType[] categorySpecs {
            get {
                return this.categorySpecsField;
            }
            set {
                this.categorySpecsField = value;
                this.RaisePropertyChanged("categorySpecs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public bool returnSpecs {
            get {
                return this.returnSpecsField;
            }
            set {
                this.returnSpecsField = value;
                this.RaisePropertyChanged("returnSpecs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecsSpecified {
            get {
                return this.returnSpecsFieldSpecified;
            }
            set {
                this.returnSpecsFieldSpecified = value;
                this.RaisePropertyChanged("returnSpecsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool newProductWithNoSpec {
            get {
                return this.newProductWithNoSpecField;
            }
            set {
                this.newProductWithNoSpecField = value;
                this.RaisePropertyChanged("newProductWithNoSpec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newProductWithNoSpecSpecified {
            get {
                return this.newProductWithNoSpecFieldSpecified;
            }
            set {
                this.newProductWithNoSpecFieldSpecified = value;
                this.RaisePropertyChanged("newProductWithNoSpecSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public bool storeVisibility {
            get {
                return this.storeVisibilityField;
            }
            set {
                this.storeVisibilityField = value;
                this.RaisePropertyChanged("storeVisibility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool storeVisibilitySpecified {
            get {
                return this.storeVisibilityFieldSpecified;
            }
            set {
                this.storeVisibilityFieldSpecified = value;
                this.RaisePropertyChanged("storeVisibilitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int storeType {
            get {
                return this.storeTypeField;
            }
            set {
                this.storeTypeField = value;
                this.RaisePropertyChanged("storeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool storeTypeSpecified {
            get {
                return this.storeTypeFieldSpecified;
            }
            set {
                this.storeTypeFieldSpecified = value;
                this.RaisePropertyChanged("storeTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int storeCategoryId {
            get {
                return this.storeCategoryIdField;
            }
            set {
                this.storeCategoryIdField = value;
                this.RaisePropertyChanged("storeCategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool storeCategoryIdSpecified {
            get {
                return this.storeCategoryIdFieldSpecified;
            }
            set {
                this.storeCategoryIdFieldSpecified = value;
                this.RaisePropertyChanged("storeCategoryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int categoryLevel {
            get {
                return this.categoryLevelField;
            }
            set {
                this.categoryLevelField = value;
                this.RaisePropertyChanged("categoryLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoryLevelSpecified {
            get {
                return this.categoryLevelFieldSpecified;
            }
            set {
                this.categoryLevelFieldSpecified = value;
                this.RaisePropertyChanged("categoryLevelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public facetFields facetFields {
            get {
                return this.facetFieldsField;
            }
            set {
                this.facetFieldsField = value;
                this.RaisePropertyChanged("facetFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public int parkCategoryId {
            get {
                return this.parkCategoryIdField;
            }
            set {
                this.parkCategoryIdField = value;
                this.RaisePropertyChanged("parkCategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parkCategoryIdSpecified {
            get {
                return this.parkCategoryIdFieldSpecified;
            }
            set {
                this.parkCategoryIdFieldSpecified = value;
                this.RaisePropertyChanged("parkCategoryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public bool parkItems {
            get {
                return this.parkItemsField;
            }
            set {
                this.parkItemsField = value;
                this.RaisePropertyChanged("parkItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parkItemsSpecified {
            get {
                return this.parkItemsFieldSpecified;
            }
            set {
                this.parkItemsFieldSpecified = value;
                this.RaisePropertyChanged("parkItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public bool returnImages {
            get {
                return this.returnImagesField;
            }
            set {
                this.returnImagesField = value;
                this.RaisePropertyChanged("returnImages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnImagesSpecified {
            get {
                return this.returnImagesFieldSpecified;
            }
            set {
                this.returnImagesFieldSpecified = value;
                this.RaisePropertyChanged("returnImagesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class categorySpecCriteriaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class specValueFacetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class specSearchResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private specValueFacetType[] facetsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("facet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public specValueFacetType[] facets {
            get {
                return this.facetsField;
            }
            set {
                this.facetsField = value;
                this.RaisePropertyChanged("facets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class searchResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string imageLinkField;
        
        private string urlField;
        
        private string titleField;
        
        private string subtitleField;
        
        private string sellerField;
        
        private string formatField;
        
        private bool hasBuyNowPriceField;
        
        private bool hasBuyNowPriceFieldSpecified;
        
        private int bidCountField;
        
        private bool bidCountFieldSpecified;
        
        private string currentPriceField;
        
        private string buyNowPriceField;
        
        private string remainingTimeField;
        
        private string shippingPaymentField;
        
        private string featureTypeField;
        
        private bool newItemField;
        
        private bool newItemFieldSpecified;
        
        private bool boldField;
        
        private bool boldFieldSpecified;
        
        private string marketPriceField;
        
        private int productCountField;
        
        private bool productCountFieldSpecified;
        
        private int soldNumField;
        
        private bool soldNumFieldSpecified;
        
        private int storeSoldNumField;
        
        private bool storeSoldNumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string imageLink {
            get {
                return this.imageLinkField;
            }
            set {
                this.imageLinkField = value;
                this.RaisePropertyChanged("imageLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
                this.RaisePropertyChanged("subtitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string seller {
            get {
                return this.sellerField;
            }
            set {
                this.sellerField = value;
                this.RaisePropertyChanged("seller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool hasBuyNowPrice {
            get {
                return this.hasBuyNowPriceField;
            }
            set {
                this.hasBuyNowPriceField = value;
                this.RaisePropertyChanged("hasBuyNowPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasBuyNowPriceSpecified {
            get {
                return this.hasBuyNowPriceFieldSpecified;
            }
            set {
                this.hasBuyNowPriceFieldSpecified = value;
                this.RaisePropertyChanged("hasBuyNowPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int bidCount {
            get {
                return this.bidCountField;
            }
            set {
                this.bidCountField = value;
                this.RaisePropertyChanged("bidCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bidCountSpecified {
            get {
                return this.bidCountFieldSpecified;
            }
            set {
                this.bidCountFieldSpecified = value;
                this.RaisePropertyChanged("bidCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string currentPrice {
            get {
                return this.currentPriceField;
            }
            set {
                this.currentPriceField = value;
                this.RaisePropertyChanged("currentPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string buyNowPrice {
            get {
                return this.buyNowPriceField;
            }
            set {
                this.buyNowPriceField = value;
                this.RaisePropertyChanged("buyNowPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string remainingTime {
            get {
                return this.remainingTimeField;
            }
            set {
                this.remainingTimeField = value;
                this.RaisePropertyChanged("remainingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string shippingPayment {
            get {
                return this.shippingPaymentField;
            }
            set {
                this.shippingPaymentField = value;
                this.RaisePropertyChanged("shippingPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string featureType {
            get {
                return this.featureTypeField;
            }
            set {
                this.featureTypeField = value;
                this.RaisePropertyChanged("featureType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool newItem {
            get {
                return this.newItemField;
            }
            set {
                this.newItemField = value;
                this.RaisePropertyChanged("newItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newItemSpecified {
            get {
                return this.newItemFieldSpecified;
            }
            set {
                this.newItemFieldSpecified = value;
                this.RaisePropertyChanged("newItemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public bool bold {
            get {
                return this.boldField;
            }
            set {
                this.boldField = value;
                this.RaisePropertyChanged("bold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boldSpecified {
            get {
                return this.boldFieldSpecified;
            }
            set {
                this.boldFieldSpecified = value;
                this.RaisePropertyChanged("boldSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string marketPrice {
            get {
                return this.marketPriceField;
            }
            set {
                this.marketPriceField = value;
                this.RaisePropertyChanged("marketPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int productCount {
            get {
                return this.productCountField;
            }
            set {
                this.productCountField = value;
                this.RaisePropertyChanged("productCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productCountSpecified {
            get {
                return this.productCountFieldSpecified;
            }
            set {
                this.productCountFieldSpecified = value;
                this.RaisePropertyChanged("productCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int soldNum {
            get {
                return this.soldNumField;
            }
            set {
                this.soldNumField = value;
                this.RaisePropertyChanged("soldNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool soldNumSpecified {
            get {
                return this.soldNumFieldSpecified;
            }
            set {
                this.soldNumFieldSpecified = value;
                this.RaisePropertyChanged("soldNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int storeSoldNum {
            get {
                return this.storeSoldNumField;
            }
            set {
                this.storeSoldNumField = value;
                this.RaisePropertyChanged("storeSoldNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool storeSoldNumSpecified {
            get {
                return this.storeSoldNumFieldSpecified;
            }
            set {
                this.storeSoldNumFieldSpecified = value;
                this.RaisePropertyChanged("storeSoldNumSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class categorySearchResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool deepestField;
        
        private bool deepestFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deepest {
            get {
                return this.deepestField;
            }
            set {
                this.deepestField = value;
                this.RaisePropertyChanged("deepest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deepestSpecified {
            get {
                return this.deepestFieldSpecified;
            }
            set {
                this.deepestFieldSpecified = value;
                this.RaisePropertyChanged("deepestSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorIdField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private string viewMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
                this.RaisePropertyChanged("errorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string viewMessage {
            get {
                return this.viewMessageField;
            }
            set {
                this.viewMessageField = value;
                this.RaisePropertyChanged("viewMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchServiceCategoryResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class baseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ackCodeField;
        
        private string responseTimeField;
        
        private errorType errorField;
        
        private string timeElapsedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ackCode {
            get {
                return this.ackCodeField;
            }
            set {
                this.ackCodeField = value;
                this.RaisePropertyChanged("ackCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public errorType error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string timeElapsed {
            get {
                return this.timeElapsedField;
            }
            set {
                this.timeElapsedField = value;
                this.RaisePropertyChanged("timeElapsed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class searchServiceResponse : baseResponse {
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool isFuzzyField;
        
        private bool isFuzzyFieldSpecified;
        
        private searchResultType[] productsField;
        
        private categorySearchResultType[] categoriesField;
        
        private specSearchResultType[] specsField;
        
        private specSearchResultType[] facetsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isFuzzy {
            get {
                return this.isFuzzyField;
            }
            set {
                this.isFuzzyField = value;
                this.RaisePropertyChanged("isFuzzy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFuzzySpecified {
            get {
                return this.isFuzzyFieldSpecified;
            }
            set {
                this.isFuzzyFieldSpecified = value;
                this.RaisePropertyChanged("isFuzzySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("product", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public searchResultType[] products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("products");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categorySearchResultType[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("categories");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("spec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public specSearchResultType[] specs {
            get {
                return this.specsField;
            }
            set {
                this.specsField = value;
                this.RaisePropertyChanged("specs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("facet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public specSearchResultType[] facets {
            get {
                return this.facetsField;
            }
            set {
                this.facetsField = value;
                this.RaisePropertyChanged("facets");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class searchServiceCategoryResponse : baseResponse {
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private categorySearchResultType[] categoriesField;
        
        private long totalProductCountField;
        
        private bool totalProductCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categorySearchResultType[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("categories");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long totalProductCount {
            get {
                return this.totalProductCountField;
            }
            set {
                this.totalProductCountField = value;
                this.RaisePropertyChanged("totalProductCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalProductCountSpecified {
            get {
                return this.totalProductCountFieldSpecified;
            }
            set {
                this.totalProductCountFieldSpecified = value;
                this.RaisePropertyChanged("totalProductCountSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.anonymous.ws.listingapi.gg.com")]
    public partial class facetFields : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] facetsField;
        
        private System.Nullable<int> limitField;
        
        private bool limitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("facet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] facets {
            get {
                return this.facetsField;
            }
            set {
                this.facetsField = value;
                this.RaisePropertyChanged("facets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitSpecified {
            get {
                return this.limitFieldSpecified;
            }
            set {
                this.limitFieldSpecified = value;
                this.RaisePropertyChanged("limitSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchServiceChannel : Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.SearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.SearchService>, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.SearchService {
        
        public SearchServiceClient() {
        }
        
        public SearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getServiceName() {
            return base.Channel.getServiceName();
        }
        
        public System.Threading.Tasks.Task<string> getServiceNameAsync() {
            return base.Channel.getServiceNameAsync();
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse search(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string lang) {
            return base.Channel.search(keyword, criteria, startOffSet, rowCount, includeDescription, withData, orderBy, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse> searchAsync(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string lang) {
            return base.Channel.searchAsync(keyword, criteria, startOffSet, rowCount, includeDescription, withData, orderBy, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse searchByVersion(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string version, string lang) {
            return base.Channel.searchByVersion(keyword, criteria, startOffSet, rowCount, includeDescription, withData, orderBy, version, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceResponse> searchByVersionAsync(string keyword, Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchCriteriaType criteria, int startOffSet, int rowCount, bool includeDescription, bool withData, string orderBy, string version, string lang) {
            return base.Channel.searchByVersionAsync(keyword, criteria, startOffSet, rowCount, includeDescription, withData, orderBy, version, lang);
        }
        
        public Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceCategoryResponse searchForCategories(string categoryCode, string lang) {
            return base.Channel.searchForCategories(categoryCode, lang);
        }
        
        public System.Threading.Tasks.Task<Ophelia.Integration.C2CMarket.GittiGidiyor.SearchService.searchServiceCategoryResponse> searchForCategoriesAsync(string categoryCode, string lang) {
            return base.Channel.searchForCategoriesAsync(categoryCode, lang);
        }
    }
}
